CLDV6211_EventEase_POE/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CLDV6211_EventEase_POE.Data;
using CLDV6211_EventEase_POE.Models;

namespace CLDV6211_EventEase_POE.Controllers
{
    public class EventsController : Controller
    {
        private readonly CLDV6211_EventEase_POEContext _context;

        public EventsController(CLDV6211_EventEase_POEContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index(string searchstring)
        {
            if (_context.Event == null)
            {
                return Problem("Entity set not found");
            }
            var events = from e in _context.Event
                           select e;

            if (!String.IsNullOrEmpty(searchstring))
            {
                events = events.Where(e => e.eventName!.ToUpper().Contains(searchstring.ToUpper()));
            }
            return View(await events.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            ViewBag.VenueId = new SelectList(_context.Venue.ToList(), "VenueId", "venueName");
            ViewBag.EventTypeId = new SelectList(_context.EventType.ToList(), "EventTypeId", "Name");
            return View();
        }

        


        // POST: Events/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public async Task<IActionResult> Create([Bind("EventId,eventName,eventDate,eventTime,description,VenueId,EventTypeId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                bool isDoubleBooked = _context.Event.Any(e => e.eventDate == @event.eventDate && e.eventTime == @event.eventTime);

                if (isDoubleBooked)
                {
                    ModelState.AddModelError("", "An event is already booked at this date and time");
                }
                else
                {
                    _context.Add(@event);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }


            ViewBag.VenueId = new SelectList(_context.Venue.ToList(), "VenueId", "venueName"); 
            ViewBag.EventTypeId = new SelectList(_context.EventType.ToList(), "EventTypeId", "Name");

            return View(@event);
        }




        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,eventName,eventDate,eventTime,description")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            bool events = await _context.Event.AnyAsync(gp => gp.EventId == id);

            if (events)
            {
                var Events = await _context.Event.FindAsync(id);
                ModelState.AddModelError("", "Cannot delete this event there are existing event records");
            
            }
            var bookingToDelete = await _context.Venue.FindAsync(id);
            _context.Venue.Remove(bookingToDelete);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Event.Any(e => e.EventId == id);
        }
        public async Task<IActionResult> Search(int? eventTypeId, DateTime? startDate, DateTime? endDate, bool onlyAvailable = false)
        {
            var events = _context.Event
                .Include(e => e.EventType)
                .Include(e => e.Venue)
                .AsQueryable();

            // Filter by event type if provided
            if (eventTypeId.HasValue)
                events = events.Where(e => e.EventTypeId == eventTypeId);

            // Filter by date range if provided
            if (startDate.HasValue && endDate.HasValue)
            {
                // Convert startDate and endDate to DateOnly to match eventDate type
                var start = DateOnly.FromDateTime(startDate.Value);
                var end = DateOnly.FromDateTime(endDate.Value);

                events = events.Where(e => e.eventDate >= start && e.eventDate <= end);
            }

            // Filter by availability if requested
            if (onlyAvailable)
            {
                // Get all bookings as IQueryable to avoid loading all into memory
                var bookings = _context.Booking.AsQueryable();

                events = events.Where(e =>
                    !bookings.Any(b =>
                        b.VenueId == e.VenueId &&
                        // Convert BookingDate (DateTime) to DateOnly for comparison with e.eventDate
                        DateOnly.FromDateTime(b.BookingDate) == e.eventDate
                    ));
            }

            ViewBag.EventTypes = await _context.EventType.ToListAsync();

            return View("Search", await events.ToListAsync());
        }

    }
}

CLDV6211_EventEase_POE/Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CLDV6211_EventEase_POE.Data;
using CLDV6211_EventEase_POE.Models;

namespace CLDV6211_EventEase_POE.Controllers
{
    public class VenuesController : Controller
    {
        private readonly CLDV6211_EventEase_POEContext _context;

        public VenuesController(CLDV6211_EventEase_POEContext context)
        {
            _context = context;
        }

        // GET: Venues
        public async Task<IActionResult> Index(string searchstring)
        {
            if (_context.Venue == null)
            {
                return Problem("Entity set not found");
            }
            var venues = from v in _context.Venue
                         select v;

            if (!String.IsNullOrEmpty(searchstring))
            {
                venues = venues.Where(v => v.venueName!.ToUpper().Contains(searchstring.ToUpper()));
            }
            return View(await venues.ToListAsync());
        }

        // GET: Venues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue
                .FirstOrDefaultAsync(m => m.VenueId == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }

        // GET: Venues/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Venues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VenueId,venueName,location,capacity,VenueDate,VenueTime")] Venue venue)
        {
            if (ModelState.IsValid)
            {


                bool isDoubleBooked = await _context.Venue.AnyAsync(v => v.VenueDate == venue.VenueDate && v.VenueTime == venue.VenueTime);

                if (isDoubleBooked)
                {
                    ModelState.AddModelError("", "An event is already booked at this date and time");
                    return View(venue);

                }
               
                _context.Venue.Add(venue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }

        // GET: Venues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue.FindAsync(id);
            if (venue == null)
            {
                return NotFound();
            }
            return View(venue);
        }

        // POST: Venues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VenueId,venueName,location,capacity,VenueDate,VenueTime")] Venue venue)
        {
            if (id != venue.VenueId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VenueExists(venue.VenueId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }

        // GET: Venues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue
                .FirstOrDefaultAsync(m => m.VenueId == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }

        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            bool venues = await _context.Venue.AnyAsync(gp => gp.VenueId == id);

            if (venues)
            {
                var Venue = await _context.Venue.FindAsync(id);
                ModelState.AddModelError("", "Cannot delete this venue as there are existing venue records");
                return View(Venue);
            }
            var bookingToDelete = await _context.Booking.FindAsync(id);
            _context.Booking.Remove(bookingToDelete);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VenueExists(int id)
        {
            return _context.Venue.Any(e => e.VenueId == id);
        }
    }
}

CLDV6211_EventEase_POE/Views/Shared/Search.cshtml
<form asp-action="Search" method="get" class="form-inline">
    <select name="eventTypeId" class="form-control">
        <option value="">All Types</option>
        @foreach (var type in ViewBag.EventTypes as List<EventType>)
        {
            <option value="@type.EventTypeId">@type.Name</option>
        }
    </select>

    <input type="date" name="startDate" class="form-control" />
    <input type="date" name="endDate" class="form-control" />

    <input type="checkbox" name="onlyAvailable" /> Only Available

    <button type="submit" class="btn btn-primary">Search</button>
</form>

<table class="table mt-3">
    @foreach (var evt in Model)
    {
        <tr>
            <td>@evt.Name</td>
            <td>@evt.EventDate.ToShortDateString()</td>
            <td>@evt.EventType.Name</td>
            <td>@evt.Venue.Name</td>
        </tr>
    }
</table>

CLDV6211_EventEase_POE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CLDV6211_EventEase_POE</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CLDV6211_EventEase_POE.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EventEase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Venues" asp-action="Index">Venues</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Bookings" asp-action="Index">Bookings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (IsSectionDefined("HomePageCards"))
            {
                @RenderSection("HomePageCards", required: false)
            }
            else
            {
                <div class="container mt-5">
                    <h1 class="text-center mb-4">Welcome to EventEase</h1>

                    <div class="row">
                        <!-- Venues Card -->
                        <div class="col-md-4 mb-4">
                            <div class="card h-100">
                                <img src="https://www.unmc.edu/eventscenter/_images/images-front-page/cover-photo--new.jpg" class="card-img-top" alt="Venues" style="height: 200px; object-fit: cover;">
                                <div class="card-body">
                                    <h5 class="card-title">Venues</h5>
                                    <p class="card-text">Browse and manage available venues</p>
                                    <a asp-controller="Venues" asp-action="Index" class="btn btn-primary">View Venues</a>
                                </div>
                            </div>
                        </div>

                        <!-- Events Card -->
                        <div class="col-md-4 mb-4">
                            <div class="card h-100">
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTNPRNryqbVMxfyWpKw_Eyot42Wo1SuCWCrg&s" class="card-img-top" alt="Events" style="height: 200px; object-fit: cover;">
                                <div class="card-body">
                                    <h5 class="card-title">Events</h5>
                                    <p class="card-text">Explore and manage events</p>
                                    <a asp-controller="Events" asp-action="Index" class="btn btn-primary">View Events</a>
                                </div>
                            </div>
                        </div>

                        <!-- Bookings Card -->
                        <div class="col-md-4 mb-4">
                            <div class="card h-100">
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLC76za9PrrqQrnC-cSSXOnlMg9E-n1P8Uxg&s" class="card-img-top" alt="Bookings" style="height: 200px; object-fit: cover;">
                                <div class="card-body">
                                    <h5 class="card-title">Bookings</h5>
                                    <p class="card-text">Manage your venue bookings</p>
                                    <a asp-controller="Bookings" asp-action="Index" class="btn btn-primary">View Bookings</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
              
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CLDV6211_EventEase_POE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>